"""Atualiza tabela indicadores

Revision ID: 04afa4d4e733
Revises: f1504d6ef14d
Create Date: 2026-07-21 15:32:44.962283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04afa4d4e733'
down_revision: Union[str, Sequence[str], None] = 'f1504d6ef14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicadores', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('indicadores', sa.Column('mes', sa.Integer(), nullable=False))
    op.add_column('indicadores', sa.Column('ano', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('indicadores_supervisao_key'), 'indicadores', type_='unique')
    op.create_foreign_key(None, 'indicadores', 'users', ['user_id'], ['id'])
    op.drop_column('indicadores', 'supervisao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('indicadores', sa.Column('supervisao', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'indicadores', type_='foreignkey')
    op.create_unique_constraint(op.f('indicadores_supervisao_key'), 'indicadores', ['supervisao'], postgresql_nulls_not_distinct=False)
    op.drop_column('indicadores', 'ano')
    op.drop_column('indicadores', 'mes')
    op.drop_column('indicadores', 'user_id')
    # ### end Alembic commands ###
