"""create ferias table

Revision ID: 2a6f43cda24a
Revises: 0e3fa0272689
Create Date: 2026-07-16 19:13:03.503805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6f43cda24a'
down_revision: Union[str, Sequence[str], None] = '0e3fa0272689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ferias',
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('folgas',
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('data_folga', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=150), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico',
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('usuario_responsavel', sa.String(length=150), nullable=False),
    sa.Column('data_evento', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico')
    op.drop_table('folgas')
    op.drop_table('ferias')
    # ### end Alembic commands ###
