"""create colaboradores table

Revision ID: 90950988c0a5
Revises: e677bac8e051
Create Date: 2026-07-16 18:44:33.132660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90950988c0a5'
down_revision: Union[str, Sequence[str], None] = 'e677bac8e051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaboradores',
    sa.Column('gestor_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('locacao', sa.String(length=100), nullable=False),
    sa.Column('placa_veiculo', sa.String(length=10), nullable=True),
    sa.Column('dia_cmc', sa.Date(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gestor_id'], ['gestores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaboradores')
    # ### end Alembic commands ###
