"""create historicos table

Revision ID: acaa0efaf7d7
Revises: 852363921c5b
Create Date: 2026-07-18 15:07:38.159397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acaa0efaf7d7'
down_revision: Union[str, Sequence[str], None] = '852363921c5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('colaborador_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('FEEDBACK', 'ELOGIO', 'ADVERTENCIA', 'TREINAMENTO', 'PROMOCAO', 'OBSERVACAO', name='tipo_historico'), nullable=False),
    sa.Column('titulo', sa.Text(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['colaborador_id'], ['colaboradores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historicos')
    # ### end Alembic commands ###
