"""create indicadores table

Revision ID: e181d131729d
Revises: acaa0efaf7d7
Create Date: 2026-07-21 09:43:43.346009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e181d131729d'
down_revision: Union[str, Sequence[str], None] = 'acaa0efaf7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supervisao', sa.String(length=100), nullable=False),
    sa.Column('qtd_pessoas', sa.Integer(), nullable=False),
    sa.Column('dias_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('dias_mes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('pontos', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('ppc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_ppc', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('falta_meta_dia', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('meta_mes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('esperado_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('falta_meta_mes', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supervisao')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicadores')
    # ### end Alembic commands ###
