"""add image and event date to historicos

Revision ID: f1504d6ef14d
Revises: e181d131729d
Create Date: 2026-07-21 09:48:06.870620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1504d6ef14d'
down_revision: Union[str, Sequence[str], None] = 'acaa0efaf7d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historicos', sa.Column('imagem_url', sa.String(length=500), nullable=True))
    op.add_column('historicos', sa.Column('data_evento', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historicos', 'data_evento')
    op.drop_column('historicos', 'imagem_url')
    # ### end Alembic commands ###
